server:
  port: 8086

spring:
  application:
    name: CONFIG-SERVICE

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Stark2301/micro-config-service/
          clone-on-start: true