spring:
  application:
    name: Api-Gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/**
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/api/v1/**
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/v1/**
  config:
    import: configserver:http://localhost:8086
server:
  port: 9091




